### PR TITLE
it fails if there is no files passed down

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by miickel** [comment]
solved with the lates version of gulp-header

**Comment by stevemao** [comment]
You still need this test incase it breaks in the future?

**Comment by stevemao** [comment]
Why tests still fail?

**Comment by miickel** [comment]
try `npm rm gulp-header && npm i gulp-header && npm test`

**Comment by stevemao** [comment]
I mean travis still fails here.

**Comment by miickel** [comment]
I guess Travis only ran once, when you submitted the test and gulp-header was updated after?

**Pull request closed without merging**
